const DATABASE_FILE = "./zooko.db";
const POST_PAGE_LIMIT = 50;
const MAX_TXT = 255;
const MAGIC_ZOOKO = "zooko:";
const MAGIC_ZOOKO_LENGTH = MAGIC_ZOOKO.length;
const MAGIC_ZMSG = "zmsg:";
const MAGIC_ZMSG_LENGTH = MAGIC_ZMSG.length;

const ZOOKO_START = 102000;

module.exports = {
  DATABASE_FILE: DATABASE_FILE,
  POST_PAGE_LIMIT: POST_PAGE_LIMIT,
  MAGIC_ZOOKO: MAGIC_ZOOKO,
  MAGIC_ZOOKO_LENGTH: MAGIC_ZOOKO_LENGTH,
  MAGIC_ZMSG: MAGIC_ZMSG,
  MAGIC_ZMSG_LENGTH: MAGIC_ZMSG_LENGTH,
  ZOOKO_START: ZOOKO_START
};
